/**
 * Deterministic GitHub identity pass.
 *
 * Scraping github.com through a search engine is the slow, lossy way to read
 * GitHub. The public REST API (no auth needed, 60 req/h unauth; GITHUB_TOKEN
 * raises it far past what one audit uses) returns things no scraper reliably
 * gets:
 *
 *   - GET /users/<login>            → real name, company, location, blog,
 *                                     bio, public email, twitter handle,
 *                                     account creation date
 *   - GET /repos/<o>/<r>/commits    → commit-author name + email. Git metadata
 *                                     leaks REAL names and emails constantly —
 *                                     people configure git with their real
 *                                     identity once and it rides every commit
 *                                     forever. This is one of the strongest
 *                                     attribution anchors available anywhere.
 *
 * Runs AFTER the web sweep (it is seeded with the sweep's ranked handles plus
 * the audited username) so the deterministic graph expansion goes:
 * Reddit handle → web sweep → cross-platform handles → GitHub identity details.
 *
 * All errors are swallowed per-request: a 404 (handle not on GitHub) or a rate
 * limit must never abort a run. On 403/429 the pass records `rateLimited` and
 * stops politely instead of hammering the API.
 */

export interface GitHubCommitAuthor {
  name: string;
  email: string;
  /** Repo the commit came from (owner/repo). */
  repo: string;
  /** ISO date of the most recent commit seen with this identity. */
  date?: string;
  /** The GitHub login the commit was attributed to (always equals the probed
   *  account login — see fetchCommitAuthors' author-login verification). */
  attributedLogin: string;
}

export interface GitHubIdentity {
  login: string;
  url: string;
  name?: string;
  company?: string;
  location?: string;
  blog?: string;
  email?: string;
  bio?: string;
  twitterUsername?: string;
  /** ISO date the GitHub account was created. */
  accountCreated?: string;
  /** Distinct git commit-author identities found across their recent repos,
   *  each VERIFIED as the account owner via the commit's GitHub author login
   *  (collaborator/bot commits are excluded — see fetchCommitAuthors). */
  commitAuthors: GitHubCommitAuthor[];
  /** Commit-attribution accounting for transparency: how many commits were
   *  scanned vs. how many were confirmed authored by THIS account. */
  commitStats: { scanned: number; attributed: number; excluded: number };
}

export interface GitHubPassResult {
  /** Logins actually queried (valid-shape, deduped). */
  queried: string[];
  identities: GitHubIdentity[];
  /** True if the pass stopped early because GitHub rate-limited us. */
  rateLimited: boolean;
}

const UA = "osint-ai/2.0 (research; github identity pass)";
const TIMEOUT_MS = 10_000;

/** GitHub login shape: no underscores/dots, ≤39 chars. Other platforms' handles
 * (john.doe, john_doe) are simply not GitHub logins — skip them pre-flight. */
const LOGIN_RE = /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/;

function headers(): Record<string, string> {
  return {
    "User-Agent": UA,
    Accept: "application/vnd.github+json",
    // Optional: unauth is 60 req/h; a token makes the pass robust on big sweeps.
    ...(process.env.GITHUB_TOKEN
      ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
      : {}),
  };
}

async function ghGet(
  url: string,
): Promise<{ status: number; json: any } | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, { headers: headers(), signal: controller.signal });
    if (res.status === 404) return { status: 404, json: null };
    if (!res.ok) return { status: res.status, json: null };
    return { status: res.status, json: await res.json() };
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/** Emails that carry no identity (generated by GitHub itself). The NAME paired
 * with a noreply email is still a real-identity leak, so only emails drop out. */
function isContentlessEmail(email: string): boolean {
  return (
    /@users\.noreply\.github\.com$/i.test(email) ||
    /@bots\.noreply\.github\.com$/i.test(email) ||
    /^dependabot\[bot\]@/i.test(email)
  );
}

/** Pure: filter raw GitHub commit objects down to those confirmed authored by
 *  `login` via the commit's resolved GitHub `author.login`. Collaborator / bot /
 *  unlinked-author commits are excluded so their identities can never be
 *  attributed to the probed account. Exported for deterministic unit testing. */
export function selectOwnerCommits(
  commits: any[],
  login: string,
  repo: string,
  seen = new Set<string>(),
): { authors: GitHubCommitAuthor[]; scanned: number; excluded: number } {
  const ownerLoginLc = login.toLowerCase();
  const authors: GitHubCommitAuthor[] = [];
  let scanned = 0;
  let excluded = 0;
  for (const c of commits) {
    scanned++;
    const name = String(c?.commit?.author?.name ?? "").trim();
    const email = String(c?.commit?.author?.email ?? "").trim();
    if (!name) continue;
    // The GitHub commits API resolves each commit to a GitHub user
    // (`c.author.login`) via the commit's configured email. ONLY commits whose
    // resolved author is THIS account can be attributed to the subject.
    const authorLogin = String(c?.author?.login ?? "").toLowerCase();
    if (authorLogin !== ownerLoginLc || /\[bot\]$/i.test(name)) {
      excluded++;
      continue;
    }
    const key = `${name.toLowerCase()} <${email.toLowerCase()}>`;
    if (seen.has(key)) continue;
    seen.add(key);
    const date = c?.commit?.author?.date;
    authors.push({
      name,
      email: isContentlessEmail(email) ? "" : email,
      repo,
      date: typeof date === "string" ? date : undefined,
      attributedLogin: login,
    });
  }
  return { authors, scanned, excluded };
}

async function fetchCommitAuthors(
  login: string,
  reposPerUser = 3,
  commitsPerRepo = 8,
  ghGetFn: typeof ghGet = ghGet,
): Promise<{ authors: GitHubCommitAuthor[]; stats: GitHubIdentity["commitStats"] }> {
  const reposRes = await ghGetFn(
    `https://api.github.com/users/${encodeURIComponent(login)}/repos?sort=pushed&per_page=10`,
  );
  if (!reposRes?.json || !Array.isArray(reposRes.json)) {
    return { authors: [], stats: { scanned: 0, attributed: 0, excluded: 0 } };
  }

  const repos = reposRes.json
    .filter((r: any) => !r?.fork && typeof r?.full_name === "string")
    .slice(0, reposPerUser) as Array<{ full_name: string }>;

  const seen = new Set<string>();
  const out: GitHubCommitAuthor[] = [];
  let scanned = 0;
  let excluded = 0;
  for (const repo of repos) {
    const commitsRes = await ghGetFn(
      `https://api.github.com/repos/${repo.full_name}/commits?per_page=${commitsPerRepo}`,
    );
    if (!commitsRes?.json || !Array.isArray(commitsRes.json)) continue;
    const pick = selectOwnerCommits(commitsRes.json, login, repo.full_name, seen);
    out.push(...pick.authors);
    scanned += pick.scanned;
    excluded += pick.excluded;
  }
  return {
    authors: out,
    stats: { scanned, attributed: out.length, excluded },
  };
}

/** Dependency-injection seams for the GitHub pass. Defaults hit the real
 *  GitHub REST API; tests/eval inject deterministic fakes. */
export interface GitHubPassDeps {
  ghGet?: (url: string) => Promise<{ status: number; json: any } | null>;
}

/** Build a GitHubPassDeps from eval fixture inputs. */
export function buildGitHubDepsFromFixture(
  profiles: Record<string, any>,
  commits: Record<string, Array<{ commit: { author: { name: string; email: string; date?: string } }; author: { login: string } | null }>>,
): GitHubPassDeps {
  return {
    ghGet: async (url) => {
      const userMatch = url.match(/\/users\/([^/?]+)/);
      if (userMatch) {
        const login = userMatch[1];
        const profile = profiles[login];
        return profile ? { status: 200, json: { ...profile, login } } : { status: 404, json: null };
      }
      const repoMatch = url.match(/\/repos\/([^/]+\/[^/]+)\/commits/);
      if (repoMatch) {
        const repo = repoMatch[1];
        const repoCommits = commits[repo];
        return repoCommits ? { status: 200, json: repoCommits } : { status: 200, json: [] };
      }
      const userReposMatch = url.match(/\/users\/([^/?]+)\/repos/);
      if (userReposMatch) {
        const login = userReposMatch[1];
        const ownedRepos = Object.keys(commits).filter((r) => r.startsWith(`${login}/`));
        return { status: 200, json: ownedRepos.map((full_name) => ({ full_name })) };
      }
      return { status: 404, json: null };
    },
  };
}

/**
 * Run the GitHub identity pass over a set of seed handles (typically the web
 * sweep's bridge/cluster/username-tier handles + the audited username).
 */
export async function runGitHubPass(
  seeds: string[],
  opts: { maxSeeds?: number; reposPerUser?: number; deps?: GitHubPassDeps } = {},
  onProgress?: (msg: string) => void,
): Promise<GitHubPassResult> {
  const maxSeeds = opts.maxSeeds ?? 8;
  const reposPerUser = opts.reposPerUser ?? 3;

  // Dedupe case-insensitively, keep the most lowercase-shaped variant seen
  // (GitHub logins are case-insensitive; the API canonicalizes for us anyway).
  const seen = new Map<string, string>();
  for (const raw of seeds) {
    const h = raw.replace(/^@/, "").trim();
    if (!LOGIN_RE.test(h)) continue;
    const key = h.toLowerCase();
    if (!seen.has(key)) seen.set(key, h);
  }
  const logins = [...seen.values()].slice(0, maxSeeds);

  const identities: GitHubIdentity[] = [];
  let rateLimited = false;
  onProgress?.(`[github-pass] Probing ${logins.length} handle(s) on the GitHub API...`);

  const doGhGet = opts.deps?.ghGet ?? ghGet;

  for (const login of logins) {
    const userRes = await doGhGet(
      `https://api.github.com/users/${encodeURIComponent(login)}`,
    );
    if (!userRes) return { queried: logins, identities, rateLimited };
    if (userRes.status === 403 || userRes.status === 429) {
      rateLimited = true;
      onProgress?.(`[github-pass] Rate-limited by GitHub (60 req/h unauth); set GITHUB_TOKEN to raise the cap.`);
      return { queried: logins, identities, rateLimited };
    }
    if (userRes.status !== 200 || !userRes.json) continue; // 404: not on GitHub

    const u = userRes.json;
    const { authors: commitAuthors, stats: commitStats } = await fetchCommitAuthors(login, reposPerUser, 8, doGhGet);
    identities.push({
      login: String(u.login ?? login),
      url: String(u.html_url ?? `https://github.com/${login}`),
      name: u.name ? String(u.name) : undefined,
      company: u.company ? String(u.company) : undefined,
      location: u.location ? String(u.location) : undefined,
      blog: u.blog ? String(u.blog) : undefined,
      email: u.email ? String(u.email).toLowerCase() : undefined,
      bio: u.bio ? String(u.bio) : undefined,
      twitterUsername: u.twitter_username ? String(u.twitter_username) : undefined,
      accountCreated: u.created_at ? String(u.created_at).slice(0, 10) : undefined,
      commitAuthors,
      commitStats,
    });

    const leaks = [
      u.name ? `name=${u.name}` : null,
      u.email ? `email=${u.email}` : null,
      u.blog ? `blog=${u.blog}` : null,
      commitAuthors.length > 0 ? `${commitAuthors.length} commit identity(ies)` : null,
    ].filter(Boolean).join(", ");
    const excl = commitStats.excluded > 0 ? ` (${commitStats.excluded} collaborator/bot commit(s) excluded)` : "";
    onProgress?.(`[github-pass] ${login}: ✔ profile found${leaks ? ` — ${leaks}` : " (no leaked fields)"}${excl}`);
  }

  return { queried: logins, identities, rateLimited };
}

/**
 * Convert the pass output into report-level identifier shapes: the public
 * profile email + every commit-author email, plus the linked twitter handle.
 * Deliberately duplicates shape with extract.ts results so the pipeline merge
 * dedupes them naturally.
 */
export function gitHubIdentifiers(result: GitHubPassResult): {
  emails: string[];
  socialHandles: Array<{ platform: string; handle: string; url: string }>;
} {
  const emails = new Set<string>();
  const handles: Array<{ platform: string; handle: string; url: string }> = [];
  const seenHandle = new Set<string>();
  for (const id of result.identities) {
    if (id.email) emails.add(id.email);
    for (const ca of id.commitAuthors) {
      if (ca.email) emails.add(ca.email.toLowerCase());
    }
    // The GitHub profile itself is a confirmed handle for this login.
    const ghKey = `github:${id.login.toLowerCase()}`;
    if (!seenHandle.has(ghKey)) {
      seenHandle.add(ghKey);
      handles.push({ platform: "github", handle: id.login, url: id.url });
    }
    if (id.twitterUsername) {
      const twKey = `x:${id.twitterUsername.toLowerCase()}`;
      if (!seenHandle.has(twKey)) {
        seenHandle.add(twKey);
        handles.push({
          platform: "x",
          handle: id.twitterUsername,
          url: `https://x.com/${id.twitterUsername}`,
        });
      }
    }
  }
  return { emails: [...emails], socialHandles: handles };
}

/** Render the pass as a markdown report block (LLM-independent). */
export function renderGitHubBlock(result: GitHubPassResult): string {
  if (result.identities.length === 0) return "";
  const lines: string[] = [];
  lines.push(`## GitHub Identity Pass`);
  lines.push(
    `*LLM-independent GitHub REST API pass over the sweep's handles — profile fields (name/company/location/blog/email) plus git commit-author identities. ${result.queried.length} login(s) probed, ${result.identities.length} found.*${result.rateLimited ? " ⚠️ stopped early (GitHub rate limit; set GITHUB_TOKEN to raise it)" : ""}`,
  );
  lines.push("");

  for (const id of result.identities) {
    lines.push(`### [\`${id.login}\`](${id.url})`);
    const fields: Array<[string, string | undefined]> = [
      ["Name", id.name],
      ["Company", id.company],
      ["Location", id.location],
      ["Blog / site", id.blog],
      ["Public email", id.email],
      ["Twitter/X", id.twitterUsername ? `@${id.twitterUsername}` : undefined],
      ["Bio", id.bio],
      ["Account created", id.accountCreated],
    ];
    for (const [label, value] of fields) {
      if (value) lines.push(`- **${label}:** ${value}`);
    }
    if (id.commitAuthors.length > 0) {
      lines.push(`- **Commit-author identities** (git metadata leaks the configured real name/email; each verified as authored by this account via its GitHub login):`);
      for (const ca of id.commitAuthors.slice(0, 6)) {
        lines.push(
          `  - \`${ca.name}${ca.email ? ` <${ca.email}>` : ""}\` — [${ca.repo}](https://github.com/${ca.repo})${ca.date ? ` (${ca.date.slice(0, 10)})` : ""}`,
        );
      }
    }
    if (id.commitStats && (id.commitStats.excluded > 0 || id.commitStats.scanned > 0)) {
      lines.push(
        `- *Commit attribution:* ${id.commitStats.scanned} commit(s) scanned, ${id.commitStats.attributed} confirmed authored by \`${id.login}\`${id.commitStats.excluded > 0 ? `, ${id.commitStats.excluded} collaborator/bot commit(s) excluded` : ""}.`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** Render the pass as GROUND-TRUTH context for the synthesis/live agent. */
export function renderGitHubContextForPrompt(result: GitHubPassResult, auditedUsername?: string): string {
  const withLeaks = result.identities.filter(
    (id) =>
      id.name || id.email || id.blog || id.commitAuthors.length > 0 ||
      id.company || id.location || id.twitterUsername,
  );
  if (withLeaks.length === 0) return "";

  const lines: string[] = [];
  lines.push("=== GITHUB IDENTITY PASS (GROUND TRUTH — from the GitHub REST API, no LLM) ===");
  lines.push("These profile fields and commit-author identities come straight from GitHub's API. Treat them as verified facts about the corresponding handle. Use real names/emails to drive further web searches (e.g. \"<name>\" <city>), attribute in Identity Resolution, and reconcile with the Reddit evidence.");
  lines.push("");
  for (const id of withLeaks) {
    lines.push(`- GitHub ${id.url}`);
    if (id.name) lines.push(`    real-name field: "${id.name}"`);
    if (id.company) lines.push(`    company: ${id.company}`);
    if (id.location) lines.push(`    location: ${id.location}`);
    if (id.blog) lines.push(`    personal site: ${id.blog}`);
    if (id.email) lines.push(`    public email: ${id.email}`);
    if (id.twitterUsername) {
      const isBridge = auditedUsername && id.twitterUsername.toLowerCase() === auditedUsername.toLowerCase();
      lines.push(`    linked X/Twitter: @${id.twitterUsername}`);
      if (isBridge && id.login.toLowerCase() !== auditedUsername.toLowerCase()) {
        lines.push(`    **BRIDGE SIGNAL**: This GitHub account (${id.login}) links to @${id.twitterUsername}, which matches the audited Reddit username. This confirms ${id.login} is the same person as u/${auditedUsername} \u2014 they renamed their handle from ${id.twitterUsername} to ${id.login} on GitHub. Search for \`${id.login}\` on Instagram, YouTube, TikTok, and other platforms to find their current profiles.`);
      }
    }
    for (const ca of id.commitAuthors.slice(0, 4)) {
      lines.push(`    git commit author: "${ca.name}${ca.email ? ` <${ca.email}>` : ""}" (repo ${ca.repo})`);
    }
  }
  lines.push("");
  lines.push("=== END GITHUB LEADS ===");
  lines.push("");
  return lines.join("\n");
}
